#by default all pods communication is allowed in namespace we are denying that
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: pavan
spec:
  podSelector: {}          # ALL pods in namespace
  policyTypes:
  - Ingress
---
# we are allowing only internal pod communication in the namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-internal
  namespace: pavan
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
---
# we are denying all the traffic going outside of the pods

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-egress
  namespace: pavan
spec:
  podSelector: {}
  policyTypes:
  - Egress
---
# we are allowing the traffic to kubesystem namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kubestem-namespace
  namespace: pavan
spec:
  podSelector: {}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 80

---
# we are allowing the traffic to other namespace
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-namespace-traffic
  namespace: pavan
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: any namespace with in the cluster
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: any namespace with in the cluster
